# Generated by Django 5.0.6 on 2024-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(default=None, upload_to=""),
        ),
    ]
