# Generated by Django 5.0.6 on 2024-05-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_transfer", "0003_remove_file_file_name_remove_file_file_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="recepient",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="file",
            name="recepients",
            field=models.CharField(default="", max_length=50),
        ),
    ]
